--- #YAML:1.0
name:               File-Locate-Iterator
version:            21
abstract:           Read "locate" database file with an iterator.
author:
    - Kevin Ryde <user42@zip.com.au>
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    constant::defer:  0
    File::FnMatch:    0
    perl:             5.006
    Scalar::Util:     0
    Test::More:       0
resources:
    homepage:  http://user42.tuxfamily.org/file-locate-iterator/index.html
    license:   http://www.gnu.org/licenses/gpl.html
no_index:
    directory:
        - t
        - inc
        - xt
        - devel
        - examples
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
optional_features:
    maximum_devel:
        description:  Stuff used variously for development.
        requires:
            Devel::Comments:     0
            Devel::TimeThis:     0
            File::Locate:        0
            File::Map:           0.38
            IO::String:          0
            Parse::CPAN::Meta:   0
            Perl6::Slurp:        0
            PerlIO:              0
            PerlIO::Layers:      0
            Pod::Simple::HTML:   0
            Scalar::Util:        0
            Smart::Comments:     0
            Sys::Mmap:           0
            Taint::Util:         0
            Test::DistManifest:  0
            Test::Pod:           1.00
            Test::YAML::Meta:    0.15
            Text::Glob:          0
            warnings::unused:    0
            YAML:                0
            YAML::Syck:          0
            YAML::Tiny:          0
            YAML::XS:            0
    maximum_examples:
        description:  Be able to run all the examples programs.
        requires:
            Iterator:          0
            Iterator::Simple:  0
            MooseX::Iterator:  0
    maximum_interoperation:
        description:  Have maximum inter-operation with other modules (optional supported other stuff).
        requires:
            File::Map:         0.38
            Iterator:          0
            Iterator::Simple:  0
            MooseX::Iterator:  0
            PerlIO::Layers:    0
    maximum_tests:
        description:  Have "make test" do as much as possible.
        requires:
            Taint::Util:   0
            Test::Weaken:  3.002
recommends:
    File::Map:       0.38
    PerlIO::Layers:  0
